name: sadaae

services:
  ### Servicio de PostgreSQL ###
  postgres:
    container_name: sadaae-postgres
    image: postgres:17.4-alpine
    env_file:
      - path: postgres/default.env
        required: true
      - path: postgres/override.env
        required: false
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    networks:
      - local_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ### Servicio de Keycloak ###
  keycloak:
    container_name: sadaae-keycloak
    image: quay.io/keycloak/keycloak:26.1.3
    build:
      context: keycloak
      target: ${TARGET:-debug}
    env_file:
      - path: keycloak/default.env
        required: true
      - path: keycloak/override.env
        required: false
    ports:
      - ${KC_PORT:-8080}:${KC_PORT:-8080}
    networks:
      - local_network
    depends_on:
      - postgres

  ### Servicio de MongoDB ###
  mongo:
    container_name: sadaae-mongo
    image: mongodb/mongodb-community-server:7.0.16-ubuntu2204
    command: --wiredTigerCacheSizeGB 1.0
    env_file:
      - path: mongo/default.env
        required: true
      - path: mongo/override.env
        required: false
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}
    networks:
      - local_network
    volumes:
      - mongo_data:/data/db
      - mongo_config_data:/data/configdb

  ### Servicio de SeaweedFS Master ###
  seaweedfs_master:
    container_name: sadaae-seaweedfs-master
    image: chrislusf/seaweedfs:3.85
    command:
      - "master"
      - "-port=${SEAWEEDFS_MASTER_PORT:-8081}"
      - "-volumeSizeLimitMB=4000"
    ports:
      - ${SEAWEEDFS_MASTER_PORT:-8081}:${SEAWEEDFS_MASTER_PORT:-8081}
    networks:
      - local_network
    volumes:
      - seaweedfs_master_data:/data

  ### Servicio de Seaweed Volume ###
  seaweedfs_volume:
    container_name: sadaae-seaweedfs-volume
    image: chrislusf/seaweedfs:3.85
    command:
      - "volume"
      - "-mserver=seaweedfs_master:${SEAWEEDFS_MASTER_PORT:-8081}"
      - "-dir=/data"
      - "-port=${SEAWEEDFS_VOLUME_PORT:-8082}"
      - "-max=4"
    ports:
      - ${SEAWEEDFS_VOLUME_PORT:-8082}:${SEAWEEDFS_VOLUME_PORT:-8082}
    networks:
      - local_network
    volumes:
      - seaweedfs_volume_data:/data
    depends_on:
      - seaweedfs_master

  ### Servicio del RESTful API ###
  api:
    container_name: sadaae-api
    image: alanelmago/sadaee-api:0.11.0
    build:
      context: api
      target: ${TARGET:-debug}
    develop:
      watch:
        - action: sync
          path: api
          target: /app
          ignore:
            - api/node_modules
    env_file:
      - path: api/default.env
        required: true
      - path: api/override.env
        required: false
    ports:
      - ${API_PORT:-3000}:${API_PORT:-3000}
    networks:
      - local_network

networks:
  local_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local
  mongo_config_data:
    driver: local
  seaweedfs_master_data:
    driver: local
  seaweedfs_volume_data:
    driver: local
